-- Compiled relations: per-store, opt-in generated SQL functions.
--
-- A store opted in with enable_compiled_relations gets, for every
-- (type, relation) of its latest model, three plain LANGUAGE sql
-- functions in a schema the application owns:
--
--   <type>__<relation>__objects   subject -> objects (list_objects)
--   <type>__<relation>__subjects  object -> subjects (final list)
--   <type>__<relation>__check     object + subject -> boolean
--
-- They are regenerated by every write_authorization_model of that
-- store, in the same transaction, and recorded in
-- fga.compiled_relation together with the strategy each relation
-- compiled to. The registry, never a name pattern, says which
-- functions the engine owns: cleanup drops exactly what is
-- registered.
--
-- Generated functions carry no SET clause (it would block
-- inlining into the caller's query), so their bodies
-- schema-qualify every table, function, type and operator
-- instead. The hand-written functions in this file keep the
-- usual SET search_path.
--
-- Strategies: each relation compiles to its own emitter.
--   delegated  same signature, body calls the generic resolver;
--              used for anything no other emitter answers exactly
--              (the reason column says why).

CREATE TABLE IF NOT EXISTS fga.compiled_store (
  store uuid NOT NULL,
  target_schema text NOT NULL,
  subject_sources jsonb,
  PRIMARY KEY (store)
);

-- One store per schema: two stores' functions would share names.
CREATE UNIQUE INDEX IF NOT EXISTS compiled_store_schema_idx
  ON fga.compiled_store (target_schema);

CREATE TABLE IF NOT EXISTS fga.compiled_relation (
  store uuid NOT NULL,
  model_id uuid NOT NULL,
  type_name text NOT NULL,
  relation_name text NOT NULL,
  objects_fn regprocedure NOT NULL,
  subjects_fn regprocedure NOT NULL,
  check_fn regprocedure NOT NULL,
  strategy text NOT NULL,
  reason text,
  PRIMARY KEY (store, model_id, type_name, relation_name)
);

-- The generated function name for one (type, relation, kind).
CREATE OR REPLACE FUNCTION fga._compiled_name(
  type_name text, relation_name text, kind text
)
RETURNS text
LANGUAGE sql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT type_name || '__' || relation_name || '__' || kind;
$$;

-- Subject validation shared by every generated function: the nil
-- uuid is refused as an id exactly like the public API, and
-- "any subject" (the type:* question) is its own flag. Returns the
-- id to match — the nil sentinel for "any subject" — so the
-- sentinel never crosses the function surface.
CREATE OR REPLACE FUNCTION fga._compiled_sid(
  subject_id uuid, any_subject boolean, subject_relation text
)
RETURNS uuid
LANGUAGE plpgsql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
BEGIN
  IF coalesce(any_subject, false) THEN
    IF subject_id IS NOT NULL THEN
      RAISE EXCEPTION 'invalid subject: p_any_subject asks about '
        'any subject and takes no subject id' USING ERRCODE = 'YF100';
    END IF;
    IF coalesce(subject_relation, '') <> '' THEN
      RAISE EXCEPTION 'invalid subject: a wildcard subject cannot '
        'carry a relation' USING ERRCODE = 'YF100';
    END IF;
    RETURN '00000000-0000-0000-0000-000000000000';
  END IF;
  IF subject_id IS NULL
     OR subject_id = '00000000-0000-0000-0000-000000000000' THEN
    RAISE EXCEPTION 'invalid user id ''%'': not a canonical uuid '
      '(fga4postgres id domain)', coalesce(subject_id::text, '')
      USING ERRCODE = 'YF100';
  END IF;
  RETURN subject_id;
END;
$$;

CREATE OR REPLACE FUNCTION fga._compiled_oid(object_id uuid)
RETURNS uuid
LANGUAGE plpgsql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
BEGIN
  IF object_id IS NULL
     OR object_id = '00000000-0000-0000-0000-000000000000' THEN
    RAISE EXCEPTION 'invalid object id ''%'': not a canonical '
      'uuid (fga4postgres id domain)', coalesce(object_id::text, '')
      USING ERRCODE = 'YF100';
  END IF;
  RETURN object_id;
END;
$$;

-- The "type:id[#relation]" / "type:*" user string of a subject.
CREATE OR REPLACE FUNCTION fga._compiled_user(
  subject_type text, subject_id uuid, subject_relation text,
  any_subject boolean
)
RETURNS text
LANGUAGE sql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT subject_type || ':' || CASE
    WHEN fga._compiled_sid(subject_id, any_subject, subject_relation)
         = '00000000-0000-0000-0000-000000000000'
    THEN '*'
    ELSE subject_id::text || CASE
      WHEN coalesce(subject_relation, '') <> ''
      THEN '#' || subject_relation ELSE '' END
  END;
$$;

-- The generic resolver behind delegated functions. The model id
-- is the one the function was compiled from, so a delegated
-- answer never comes from another model.
CREATE OR REPLACE FUNCTION fga._compiled_check(
  store_id uuid, model_id uuid, object_type text, relation text,
  object_id uuid, subject_type text, subject_id uuid,
  subject_relation text, any_subject boolean,
  context jsonb, contextual_tuples jsonb
)
RETURNS boolean
LANGUAGE sql
STABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT (fga.check(store_id, jsonb_build_object(
    'authorization_model_id', model_id::text,
    'tuple_key', jsonb_build_object(
      'object', object_type || ':' || fga._compiled_oid(object_id),
      'relation', relation,
      'user', fga._compiled_user(subject_type, subject_id,
                                 subject_relation, any_subject)),
    'context', context,
    'contextual_tuples', jsonb_build_object(
      'tuple_keys', coalesce(contextual_tuples, '[]'::jsonb))
  )) ->> 'allowed')::boolean;
$$;

-- Delegated objects go through list_objects, so they carry its
-- result cap until an uncapped resolver entry point exists.
CREATE OR REPLACE FUNCTION fga._compiled_objects(
  store_id uuid, model_id uuid, object_type text, relation text,
  subject_type text, subject_id uuid, subject_relation text,
  any_subject boolean, context jsonb, contextual_tuples jsonb
)
RETURNS SETOF uuid
LANGUAGE sql
STABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT split_part(o, ':', 2)::uuid
  FROM jsonb_array_elements_text(fga.list_objects(store_id,
    jsonb_build_object(
      'authorization_model_id', model_id::text,
      'type', object_type,
      'relation', relation,
      'user', fga._compiled_user(subject_type, subject_id,
                                 subject_relation, any_subject),
      'context', context,
      'contextual_tuples', jsonb_build_object(
        'tuple_keys', coalesce(contextual_tuples, '[]'::jsonb))
    )) -> 'objects') AS o;
$$;

-- The rows of a registered subject source ("schema.table(column)").
CREATE OR REPLACE FUNCTION fga._compiled_source_ids(
  store_id uuid, subject_type text
)
RETURNS SETOF uuid
LANGUAGE plpgsql
STABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
DECLARE
  src text;
  m text[];
BEGIN
  SELECT cs.subject_sources ->> subject_type INTO src
  FROM fga.compiled_store cs WHERE cs.store = store_id;
  IF src IS NULL THEN
    RAISE EXCEPTION 'no subject source registered for type ''%'': '
      'a wildcard grant cannot be expanded into a list of subjects',
      subject_type USING ERRCODE = 'YF100';
  END IF;
  m := fga._compiled_parse_source(src);
  RETURN QUERY EXECUTE format('SELECT %I FROM %I.%I',
    m[3], m[1], m[2]);
END;
$$;

-- Delegated subjects: list_users answers, and its users become the
-- final list — a userset filter yields the userset ids, and a
-- typed wildcard expands over the registered subject source,
-- keeping only the subjects check allows (a wildcard may carry
-- exclusions list_users does not show).
CREATE OR REPLACE FUNCTION fga._compiled_subjects(
  store_id uuid, model_id uuid, object_type text, relation text,
  object_id uuid, subject_type text, subject_relation text,
  context jsonb, contextual_tuples jsonb
)
RETURNS SETOF uuid
LANGUAGE plpgsql
STABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
DECLARE
  users jsonb;
  filter jsonb := jsonb_build_object('type', subject_type);
BEGIN
  IF coalesce(subject_relation, '') <> '' THEN
    filter := filter || jsonb_build_object(
      'relation', subject_relation);
  END IF;
  users := fga.list_users(store_id, jsonb_build_object(
    'authorization_model_id', model_id::text,
    'object', jsonb_build_object(
      'type', object_type, 'id', fga._compiled_oid(object_id)),
    'relation', relation,
    'user_filters', jsonb_build_array(filter),
    'context', context,
    'contextual_tuples', coalesce(contextual_tuples, '[]'::jsonb)
  )) -> 'users';

  RETURN QUERY
  SELECT coalesce(u -> 'object' ->> 'id',
                  u -> 'userset' ->> 'id')::uuid
  FROM jsonb_array_elements(users) AS u
  WHERE u ? 'object' OR u ? 'userset';

  IF EXISTS (
    SELECT FROM jsonb_array_elements(users) AS u
    WHERE u ? 'wildcard'
  ) THEN
    RETURN QUERY
    SELECT s.id FROM fga._compiled_source_ids(
      store_id, subject_type) AS s(id)
    WHERE fga._compiled_check(store_id, model_id, object_type,
      relation, object_id, subject_type, s.id, '', false,
      context, contextual_tuples);
  END IF;
END;
$$;

-- "schema.table(column)" -> {schema, table, column}; NULL when the
-- text does not have that shape.
CREATE OR REPLACE FUNCTION fga._compiled_parse_source(src text)
RETURNS text[]
LANGUAGE sql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT regexp_match(src,
    '^([A-Za-z_][A-Za-z0-9_$]*)\.([A-Za-z_][A-Za-z0-9_$]*)'
    '\(([A-Za-z_][A-Za-z0-9_$]*)\)$');
$$;

-- The generated signatures, one per kind. Every type is qualified
-- so the signature text doubles as a regprocedure literal.
CREATE OR REPLACE FUNCTION fga._compiled_params(kind text)
RETURNS text
LANGUAGE sql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT CASE kind
    WHEN 'objects' THEN
      'p_subject_type pg_catalog.text, p_subject_id pg_catalog.uuid, '
      'p_subject_relation pg_catalog.text DEFAULT '''', '
      'p_any_subject pg_catalog.bool DEFAULT false, '
      'p_context pg_catalog.jsonb DEFAULT ''{}'', '
      'p_contextual_tuples pg_catalog.jsonb DEFAULT ''[]'''
    WHEN 'subjects' THEN
      'p_object pg_catalog.uuid, p_subject_type pg_catalog.text, '
      'p_subject_relation pg_catalog.text DEFAULT '''', '
      'p_context pg_catalog.jsonb DEFAULT ''{}'', '
      'p_contextual_tuples pg_catalog.jsonb DEFAULT ''[]'''
    WHEN 'check' THEN
      'p_object pg_catalog.uuid, p_subject_type pg_catalog.text, '
      'p_subject_id pg_catalog.uuid, '
      'p_subject_relation pg_catalog.text DEFAULT '''', '
      'p_any_subject pg_catalog.bool DEFAULT false, '
      'p_context pg_catalog.jsonb DEFAULT ''{}'', '
      'p_contextual_tuples pg_catalog.jsonb DEFAULT ''[]'''
  END;
$$;

CREATE OR REPLACE FUNCTION fga._compiled_arg_types(kind text)
RETURNS text
LANGUAGE sql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT CASE kind
    WHEN 'objects' THEN
      'pg_catalog.text, pg_catalog.uuid, pg_catalog.text, '
      'pg_catalog.bool, pg_catalog.jsonb, pg_catalog.jsonb'
    WHEN 'subjects' THEN
      'pg_catalog.uuid, pg_catalog.text, pg_catalog.text, '
      'pg_catalog.jsonb, pg_catalog.jsonb'
    WHEN 'check' THEN
      'pg_catalog.uuid, pg_catalog.text, pg_catalog.uuid, '
      'pg_catalog.text, pg_catalog.bool, pg_catalog.jsonb, '
      'pg_catalog.jsonb'
  END;
$$;

-- The function's definition around a body. LANGUAGE sql, STABLE,
-- SECURITY INVOKER and no SET clause: the shape PostgreSQL inlines.
CREATE OR REPLACE FUNCTION fga._compiled_ddl(
  target text, name text, kind text, body text
)
RETURNS text
LANGUAGE sql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT format(
    'CREATE OR REPLACE FUNCTION %I.%I(%s) RETURNS %s '
    'LANGUAGE sql STABLE PARALLEL SAFE SECURITY INVOKER AS %L',
    target, name, fga._compiled_params(kind),
    CASE kind WHEN 'check' THEN 'pg_catalog.bool'
              ELSE 'SETOF pg_catalog.uuid' END,
    body);
$$;

CREATE OR REPLACE FUNCTION fga._compiled_comment(
  store_id uuid, model_id uuid, type_name text, relation_name text,
  kind text, strategy text, reason text
)
RETURNS text
LANGUAGE sql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT format(
    'Compiled relation function. type: %s; relation: %s; kind: %s; '
    'store: %s; model id: %s; strategy: %s%s. Generated by '
    'fga4postgres from the authorization model — do not edit; '
    'every model write replaces it.',
    type_name, relation_name, kind, store_id, model_id, strategy,
    CASE WHEN reason IS NOT NULL THEN ' (' || reason || ')'
         ELSE '' END);
$$;

-- The delegated emitter: the generic resolver behind the generated
-- signature.
CREATE OR REPLACE FUNCTION fga._compiled_emit_delegated(
  store_id uuid, model_id uuid, type_name text, relation_name text,
  kind text
)
RETURNS text
LANGUAGE sql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT CASE kind
    WHEN 'objects' THEN format(
      'SELECT x FROM fga._compiled_objects(%L::pg_catalog.uuid, '
      '%L::pg_catalog.uuid, %L, %L, p_subject_type, p_subject_id, '
      'p_subject_relation, p_any_subject, p_context, '
      'p_contextual_tuples) AS x',
      store_id, model_id, type_name, relation_name)
    WHEN 'subjects' THEN format(
      'SELECT x FROM fga._compiled_subjects(%L::pg_catalog.uuid, '
      '%L::pg_catalog.uuid, %L, %L, p_object, p_subject_type, '
      'p_subject_relation, p_context, p_contextual_tuples) AS x',
      store_id, model_id, type_name, relation_name)
    WHEN 'check' THEN format(
      'SELECT fga._compiled_check(%L::pg_catalog.uuid, '
      '%L::pg_catalog.uuid, %L, %L, p_object, p_subject_type, '
      'p_subject_id, p_subject_relation, p_any_subject, p_context, '
      'p_contextual_tuples)',
      store_id, model_id, type_name, relation_name)
  END;
$$;

-- The strategy of every relation of a model, with the reason a
-- relation is delegated and the order to create functions in
-- (callees before callers).
CREATE OR REPLACE FUNCTION fga._compiled_plan(
  store_id uuid, model_id uuid
)
RETURNS TABLE (type_name text, relation_name text, strategy text,
               reason text, ord integer)
LANGUAGE sql
STABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT r.type_name, r.relation_name, 'delegated',
         'no compiled strategy yet', 0
  FROM fga.model_relation r
  WHERE r.store = store_id AND r.model_id = _compiled_plan.model_id;
$$;

-- One relation's three functions, as names and definitions.
CREATE OR REPLACE FUNCTION fga._compiled_functions(
  store_id uuid, model_id uuid, target text
)
RETURNS TABLE (type_name text, relation_name text, kind text,
               name text, sig text, ddl text, strategy text,
               reason text, ord integer)
LANGUAGE sql
STABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT p.type_name, p.relation_name, k.kind, n.name,
    format('%I.%I(%s)', target, n.name,
           fga._compiled_arg_types(k.kind)),
    fga._compiled_ddl(target, n.name, k.kind,
      CASE p.strategy
        WHEN 'delegated' THEN fga._compiled_emit_delegated(
          store_id, model_id, p.type_name, p.relation_name, k.kind)
      END),
    p.strategy, p.reason, p.ord
  FROM fga._compiled_plan(store_id, model_id) AS p
  CROSS JOIN (VALUES ('objects'), ('subjects'), ('check')) AS k(kind)
  CROSS JOIN LATERAL (SELECT fga._compiled_name(
    p.type_name, p.relation_name, k.kind) AS name) AS n;
$$;

-- Drops every registered function of a store and its registry
-- rows. Only registered functions: anything else in the schema
-- belongs to the application.
CREATE OR REPLACE FUNCTION fga._compiled_drop(store_id uuid)
RETURNS void
LANGUAGE plpgsql
VOLATILE
SET search_path = fga, pg_temp
AS $$
DECLARE
  fn regprocedure;
BEGIN
  FOR fn IN
    SELECT DISTINCT v.f
    FROM fga.compiled_relation r,
         LATERAL (VALUES (r.objects_fn), (r.subjects_fn),
                         (r.check_fn)) AS v(f)
    WHERE r.store = store_id
  LOOP
    EXECUTE format('DROP FUNCTION %s', fn);
  END LOOP;
  DELETE FROM fga.compiled_relation WHERE store = store_id;
END;
$$;

-- Regenerates every function of an opted-in store from its latest
-- model, in the caller's transaction. A no-op for stores that did
-- not opt in.
--
-- Functions that survive a model change are replaced in place
-- (CREATE OR REPLACE keeps their oid, so a cached plan that inlined
-- one is invalidated and re-planned rather than left pointing at a
-- dropped function); only registered functions the new model no
-- longer has are dropped. A same-signature function the engine did
-- not register belongs to the application: it refuses the model
-- write instead of being overwritten.
CREATE OR REPLACE FUNCTION fga._compiled_generate(store_id uuid)
RETURNS void
LANGUAGE plpgsql
VOLATILE
SET search_path = fga, pg_temp
AS $$
DECLARE
  target text;
  mid uuid;
  fns jsonb;
  fn record;
  clash text;
BEGIN
  SELECT cs.target_schema INTO target
  FROM fga.compiled_store cs WHERE cs.store = store_id;
  IF NOT FOUND THEN
    RETURN;
  END IF;

  SELECT m.id INTO mid FROM fga.model m
  WHERE m.store = store_id ORDER BY m.id DESC LIMIT 1;

  SELECT coalesce(jsonb_agg(to_jsonb(f) ORDER BY f.ord, f.name),
                  '[]')
  INTO fns
  FROM fga._compiled_functions(store_id, mid, target) AS f
  WHERE mid IS NOT NULL;

  SELECT f ->> 'name' INTO clash
  FROM jsonb_array_elements(fns) AS f
  GROUP BY f ->> 'name' HAVING count(*) > 1 LIMIT 1;
  IF clash IS NOT NULL THEN
    RAISE EXCEPTION 'compiled relations: two relations would share '
      'the function name %', clash USING ERRCODE = 'YF156';
  END IF;

  -- Drop what was registered and is no longer generated.
  FOR fn IN
    SELECT DISTINCT v.f
    FROM fga.compiled_relation r,
         LATERAL (VALUES (r.objects_fn), (r.subjects_fn),
                         (r.check_fn)) AS v(f)
    WHERE r.store = store_id
      AND NOT EXISTS (
        SELECT FROM jsonb_array_elements(fns) AS g
        WHERE to_regprocedure(g ->> 'sig') = v.f)
  LOOP
    EXECUTE format('DROP FUNCTION %s', fn.f);
  END LOOP;

  SELECT g ->> 'sig' INTO clash
  FROM jsonb_array_elements(fns) AS g
  WHERE to_regprocedure(g ->> 'sig') IS NOT NULL
    AND NOT EXISTS (
      SELECT FROM fga.compiled_relation r
      WHERE r.store = store_id
        AND to_regprocedure(g ->> 'sig')
              IN (r.objects_fn, r.subjects_fn, r.check_fn))
  LIMIT 1;
  IF clash IS NOT NULL THEN
    RAISE EXCEPTION 'compiled relations: function % exists and was '
      'not generated by fga4postgres', clash
      USING ERRCODE = 'YF156';
  END IF;

  DELETE FROM fga.compiled_relation WHERE store = store_id;

  FOR fn IN
    SELECT * FROM jsonb_to_recordset(fns) AS x(
      type_name text, relation_name text, kind text, name text,
      sig text, ddl text, strategy text, reason text)
  LOOP
    EXECUTE fn.ddl;
    EXECUTE format('COMMENT ON FUNCTION %s IS %L', fn.sig,
      fga._compiled_comment(store_id, mid, fn.type_name,
        fn.relation_name, fn.kind, fn.strategy, fn.reason));
  END LOOP;

  INSERT INTO fga.compiled_relation
  SELECT store_id, mid, x.type_name, x.relation_name,
    max(x.sig) FILTER (WHERE x.kind = 'objects')::regprocedure,
    max(x.sig) FILTER (WHERE x.kind = 'subjects')::regprocedure,
    max(x.sig) FILTER (WHERE x.kind = 'check')::regprocedure,
    min(x.strategy), min(x.reason)
  FROM jsonb_to_recordset(fns) AS x(
    type_name text, relation_name text, kind text, sig text,
    strategy text, reason text)
  GROUP BY x.type_name, x.relation_name;
END;
$$;

-- Opts a store in (or changes its subject sources) and generates
-- its functions for the latest model right away. The schema must
-- already exist: the application creates and owns it, so the
-- engine needs no database-level CREATE and a mistyped name is an
-- error rather than a new empty schema.
CREATE OR REPLACE FUNCTION fga.enable_compiled_relations(
  store uuid,
  target_schema text,
  subject_sources jsonb DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
VOLATILE
SET search_path = fga, pg_temp
AS $$
DECLARE
  src record;
  m text[];
BEGIN
  IF NOT EXISTS (
    SELECT FROM fga.store s
    WHERE s.id = enable_compiled_relations.store
  ) THEN
    RAISE EXCEPTION 'store % not found', enable_compiled_relations.store
      USING ERRCODE = 'YF502';
  END IF;
  IF target_schema IN ('fga', 'cel', 'information_schema')
     OR target_schema LIKE 'pg\_%' THEN
    RAISE EXCEPTION 'schema ''%'' is reserved: compiled relations '
      'need a schema of their own', target_schema
      USING ERRCODE = 'YF100';
  END IF;
  IF NOT EXISTS (
    SELECT FROM pg_namespace n WHERE n.nspname = target_schema
  ) THEN
    RAISE EXCEPTION 'schema ''%'' does not exist: create it before '
      'enabling compiled relations', target_schema
      USING ERRCODE = 'YF100';
  END IF;
  IF EXISTS (
    SELECT FROM fga.compiled_store cs
    WHERE cs.target_schema = enable_compiled_relations.target_schema
      AND cs.store <> enable_compiled_relations.store
  ) THEN
    RAISE EXCEPTION 'schema ''%'' already holds another store''s '
      'compiled relations', target_schema USING ERRCODE = 'YF100';
  END IF;

  IF subject_sources IS NOT NULL THEN
    IF jsonb_typeof(subject_sources) <> 'object' THEN
      RAISE EXCEPTION 'subject_sources must be a json object'
        USING ERRCODE = 'YF100';
    END IF;
    FOR src IN SELECT * FROM jsonb_each(subject_sources) LOOP
      m := fga._compiled_parse_source(src.value #>> '{}');
      IF jsonb_typeof(src.value) <> 'string' OR m IS NULL
         OR NOT EXISTS (
           SELECT FROM pg_attribute a
           WHERE a.attrelid = to_regclass(
                   format('%I.%I', m[1], m[2]))
             AND a.attname = m[3] AND NOT a.attisdropped
             AND a.atttypid = 'uuid'::regtype
         )
      THEN
        RAISE EXCEPTION 'subject source for type ''%'' must name '
          'an existing uuid column as schema.table(column), got %',
          src.key, src.value USING ERRCODE = 'YF100';
      END IF;
    END LOOP;
  END IF;

  -- A different schema means the old functions go first.
  IF EXISTS (
    SELECT FROM fga.compiled_store cs
    WHERE cs.store = enable_compiled_relations.store
      AND cs.target_schema <> enable_compiled_relations.target_schema
  ) THEN
    PERFORM fga._compiled_drop(enable_compiled_relations.store);
  END IF;

  INSERT INTO fga.compiled_store AS cs
  VALUES (enable_compiled_relations.store, target_schema,
          subject_sources)
  ON CONFLICT ON CONSTRAINT compiled_store_pkey DO UPDATE
  SET target_schema = excluded.target_schema,
      subject_sources = excluded.subject_sources;

  PERFORM fga._compiled_generate(enable_compiled_relations.store);
END;
$$;

-- Opts a store out: drops exactly its registered functions.
CREATE OR REPLACE FUNCTION fga.disable_compiled_relations(
  store uuid
)
RETURNS void
LANGUAGE plpgsql
VOLATILE
SET search_path = fga, pg_temp
AS $$
BEGIN
  PERFORM fga._compiled_drop(disable_compiled_relations.store);
  DELETE FROM fga.compiled_store cs
  WHERE cs.store = disable_compiled_relations.store;
END;
$$;
