-- Compiled relations: per-store, opt-in generated SQL functions.
--
-- A store opted in with enable_compiled_relations gets, for every
-- (type, relation) of its latest model, three plain LANGUAGE sql
-- functions in a schema the application owns:
--
--   <type>__<relation>__objects   subject -> objects (list_objects)
--   <type>__<relation>__subjects  object -> subjects (final list)
--   <type>__<relation>__check     object + subject -> boolean
--
-- They are regenerated by every write_authorization_model of that
-- store, in the same transaction, and recorded in
-- fga.compiled_relation together with the strategy each relation
-- compiled to. The registry, never a name pattern, says which
-- functions the engine owns: cleanup drops exactly what is
-- registered.
--
-- Generated functions carry no SET clause (it would block
-- inlining into the caller's query), so their bodies
-- schema-qualify every table, function, type and operator
-- instead. The hand-written functions in this file keep the
-- usual SET search_path.
--
-- Strategies: each relation compiles to its own emitter.
--   flattened  a UNION of fixed joins over fga.tuple (direct
--              grants, wildcards, usersets, computed usersets,
--              tuple-to-userset) for relations without cycles,
--              set operations or conditions;
--   recursive  a WITH RECURSIVE walk over the tuple graph for
--              relations on (or reaching) a cycle of the relation
--              graph, or deep enough to meet check's depth limit;
--   delegated  same signature, body calls the generic resolver;
--              used for anything no other emitter answers exactly
--              (the reason column says why).

CREATE TABLE IF NOT EXISTS fga.compiled_store (
  store uuid NOT NULL,
  target_schema text NOT NULL,
  subject_sources jsonb,
  PRIMARY KEY (store)
);

-- One store per schema: two stores' functions would share names.
CREATE UNIQUE INDEX IF NOT EXISTS compiled_store_schema_idx
  ON fga.compiled_store (target_schema);

CREATE TABLE IF NOT EXISTS fga.compiled_relation (
  store uuid NOT NULL,
  model_id uuid NOT NULL,
  type_name text NOT NULL,
  relation_name text NOT NULL,
  objects_fn regprocedure NOT NULL,
  subjects_fn regprocedure NOT NULL,
  check_fn regprocedure NOT NULL,
  strategy text NOT NULL,
  reason text,
  PRIMARY KEY (store, model_id, type_name, relation_name)
);

-- The generated function name for one (type, relation, kind)
-- (decision 11). Readable when both source names are plain
-- lower-case words joined by single underscores and the result
-- fits PostgreSQL's 63-byte identifiers; otherwise a sanitised
-- prefix, then 8 hex of a hash of the exact names, then the kind.
-- The plain form excludes "__" and leading or trailing "_" in the
-- source names, so two different pairs can never join into the
-- same readable name; the generator still refuses any collision.
CREATE OR REPLACE FUNCTION fga._compiled_name(
  type_name text, relation_name text, kind text
)
RETURNS text
LANGUAGE sql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT CASE
    WHEN type_name ~ '^[a-z][a-z0-9]*(_[a-z0-9]+)*$'
     AND relation_name ~ '^[a-z][a-z0-9]*(_[a-z0-9]+)*$'
     AND octet_length(plain) <= 63
    THEN plain
    ELSE left(
      regexp_replace(lower(type_name || '__' || relation_name),
        '[^abcdefghijklmnopqrstuvwxyz0123456789_]', '_', 'g'),
      63 - octet_length(suffix)) || suffix
  END
  FROM (SELECT
    type_name || '__' || relation_name || '__' || kind AS plain,
    '_' || left(md5(type_name || '#' || relation_name || '#' || kind),
                8) || '_' || kind AS suffix) AS n;
$$;

-- Subject validation shared by every generated function: the nil
-- uuid is refused as an id exactly like the public API, and
-- "any subject" (the type:* question) is its own flag. Returns the
-- id to match — the nil sentinel for "any subject" — so the
-- sentinel never crosses the function surface.
CREATE OR REPLACE FUNCTION fga._compiled_sid(
  subject_id uuid, any_subject boolean, subject_relation text
)
RETURNS uuid
LANGUAGE plpgsql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
BEGIN
  IF any_subject IS NULL THEN
    RAISE EXCEPTION 'invalid subject: p_any_subject must not be null'
      USING ERRCODE = 'YF100';
  END IF;
  IF any_subject THEN
    IF subject_id IS NOT NULL THEN
      RAISE EXCEPTION 'invalid subject: p_any_subject asks about '
        'any subject and takes no subject id' USING ERRCODE = 'YF100';
    END IF;
    IF coalesce(subject_relation, '') <> '' THEN
      RAISE EXCEPTION 'invalid subject: a wildcard subject cannot '
        'carry a relation' USING ERRCODE = 'YF100';
    END IF;
    RETURN '00000000-0000-0000-0000-000000000000';
  END IF;
  IF subject_id IS NULL
     OR subject_id = '00000000-0000-0000-0000-000000000000' THEN
    RAISE EXCEPTION 'invalid user id ''%'': not a canonical uuid '
      '(fga4postgres id domain)', coalesce(subject_id::text, '')
      USING ERRCODE = 'YF100';
  END IF;
  RETURN subject_id;
END;
$$;

CREATE OR REPLACE FUNCTION fga._compiled_oid(object_id uuid)
RETURNS uuid
LANGUAGE plpgsql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
BEGIN
  IF object_id IS NULL
     OR object_id = '00000000-0000-0000-0000-000000000000' THEN
    RAISE EXCEPTION 'invalid object id ''%'': not a canonical '
      'uuid (fga4postgres id domain)', coalesce(object_id::text, '')
      USING ERRCODE = 'YF100';
  END IF;
  RETURN object_id;
END;
$$;

-- The "type:id[#relation]" / "type:*" user string of a subject.
CREATE OR REPLACE FUNCTION fga._compiled_user(
  subject_type text, subject_id uuid, subject_relation text,
  any_subject boolean
)
RETURNS text
LANGUAGE sql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT subject_type || ':' || CASE
    WHEN fga._compiled_sid(subject_id, any_subject, subject_relation)
         = '00000000-0000-0000-0000-000000000000'
    THEN '*'
    ELSE subject_id::text || CASE
      WHEN coalesce(subject_relation, '') <> ''
      THEN '#' || subject_relation ELSE '' END
  END;
$$;

-- The generic resolver behind delegated functions. The model id
-- is the one the function was compiled from, so a delegated
-- answer never comes from another model.
CREATE OR REPLACE FUNCTION fga._compiled_check(
  store_id uuid, model_id uuid, object_type text, relation text,
  object_id uuid, subject_type text, subject_id uuid,
  subject_relation text, any_subject boolean,
  context jsonb, contextual_tuples jsonb
)
RETURNS boolean
LANGUAGE sql
STABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT (fga.check(store_id, jsonb_build_object(
    'authorization_model_id', model_id::text,
    'tuple_key', jsonb_build_object(
      'object', object_type || ':' || fga._compiled_oid(object_id),
      'relation', relation,
      'user', fga._compiled_user(subject_type, subject_id,
                                 subject_relation, any_subject)),
    'context', context,
    'contextual_tuples', jsonb_build_object(
      'tuple_keys', coalesce(contextual_tuples, '[]'::jsonb))
  )) ->> 'allowed')::boolean;
$$;

-- Delegated objects go through streamed_list_objects, which is
-- uncapped like every generated __objects.
CREATE OR REPLACE FUNCTION fga._compiled_objects(
  store_id uuid, model_id uuid, object_type text, relation text,
  subject_type text, subject_id uuid, subject_relation text,
  any_subject boolean, context jsonb, contextual_tuples jsonb
)
RETURNS SETOF uuid
LANGUAGE sql
STABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT split_part(o ->> 'object', ':', 2)::uuid
  FROM fga.streamed_list_objects(store_id,
    jsonb_build_object(
      'authorization_model_id', model_id::text,
      'type', object_type,
      'relation', relation,
      'user', fga._compiled_user(subject_type, subject_id,
                                 subject_relation, any_subject),
      'context', context,
      'contextual_tuples', jsonb_build_object(
        'tuple_keys', coalesce(contextual_tuples, '[]'::jsonb))
    )) AS o;
$$;

-- The rows of a registered subject source ("schema.table(column)").
CREATE OR REPLACE FUNCTION fga._compiled_source_ids(
  store_id uuid, subject_type text
)
RETURNS SETOF uuid
LANGUAGE plpgsql
STABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
DECLARE
  src text;
  m text[];
BEGIN
  SELECT cs.subject_sources ->> subject_type INTO src
  FROM fga.compiled_store cs WHERE cs.store = store_id;
  IF src IS NULL THEN
    RAISE EXCEPTION 'no subject source registered for type ''%'': '
      'a wildcard grant cannot be expanded into a list of subjects',
      subject_type USING ERRCODE = 'YF100';
  END IF;
  m := fga._compiled_parse_source(src);
  RETURN QUERY EXECUTE format('SELECT %I FROM %I.%I',
    m[3], m[1], m[2]);
END;
$$;

-- Delegated subjects: the generic list_users search, uncapped,
-- turned into the final list __subjects promises (decision 8).
-- list_users answers in upstream's shape, so its users are mapped:
-- an object user is its id; a userset user (the filter names a
-- relation) is the userset's id; and a typed wildcard expands over
-- the registered subject source, keeping only the subjects check
-- allows — upstream's shape hides a wildcard's exclusions (user:*
-- but not bob is just user:*), and check is what applies them.
CREATE OR REPLACE FUNCTION fga._compiled_subjects(
  store_id uuid, model_id uuid, object_type text, relation text,
  object_id uuid, subject_type text, subject_relation text,
  context jsonb, contextual_tuples jsonb
)
RETURNS SETOF uuid
LANGUAGE plpgsql
STABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
DECLARE
  users jsonb;
  filter jsonb := jsonb_build_object('type', subject_type);
BEGIN
  IF coalesce(subject_relation, '') <> '' THEN
    filter := filter || jsonb_build_object(
      'relation', subject_relation);
  END IF;
  users := fga._list_users(store_id, jsonb_build_object(
    'authorization_model_id', model_id::text,
    'object', jsonb_build_object(
      'type', object_type, 'id', fga._compiled_oid(object_id)),
    'relation', relation,
    'user_filters', jsonb_build_array(filter),
    'context', context,
    'contextual_tuples', coalesce(contextual_tuples, '[]'::jsonb)
  ), 0) -> 'users';

  IF NOT EXISTS (
    SELECT FROM jsonb_array_elements(users) AS u
    WHERE u ? 'wildcard'
  ) THEN
    RETURN QUERY
    SELECT coalesce(u -> 'object' ->> 'id',
                    u -> 'userset' ->> 'id')::uuid
    FROM jsonb_array_elements(users) AS u
    WHERE u ? 'object' OR u ? 'userset';
    RETURN;
  END IF;

  RETURN QUERY
  SELECT (u -> 'object' ->> 'id')::uuid
  FROM jsonb_array_elements(users) AS u
  WHERE u ? 'object'
  UNION
  SELECT s.id FROM fga._compiled_source_ids(
    store_id, subject_type) AS s(id)
  WHERE fga._compiled_check(store_id, model_id, object_type,
    relation, object_id, subject_type, s.id, '', false,
    context, contextual_tuples);
END;
$$;

-- "schema.table(column)" -> {schema, table, column}; NULL when the
-- text does not have that shape.
CREATE OR REPLACE FUNCTION fga._compiled_parse_source(src text)
RETURNS text[]
LANGUAGE sql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT regexp_match(src,
    '^([A-Za-z_][A-Za-z0-9_$]*)\.([A-Za-z_][A-Za-z0-9_$]*)'
    '\(([A-Za-z_][A-Za-z0-9_$]*)\)$');
$$;

-- The generated signatures, one per kind. Every type is qualified
-- so the signature text doubles as a regprocedure literal.
CREATE OR REPLACE FUNCTION fga._compiled_params(kind text)
RETURNS text
LANGUAGE sql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT CASE kind
    WHEN 'objects' THEN
      'p_subject_type pg_catalog.text, p_subject_id pg_catalog.uuid, '
      'p_subject_relation pg_catalog.text DEFAULT '''', '
      'p_any_subject pg_catalog.bool DEFAULT false, '
      'p_context pg_catalog.jsonb DEFAULT ''{}'', '
      'p_contextual_tuples pg_catalog.jsonb DEFAULT ''[]'''
    WHEN 'subjects' THEN
      'p_object pg_catalog.uuid, p_subject_type pg_catalog.text, '
      'p_subject_relation pg_catalog.text DEFAULT '''', '
      'p_context pg_catalog.jsonb DEFAULT ''{}'', '
      'p_contextual_tuples pg_catalog.jsonb DEFAULT ''[]'''
    WHEN 'check' THEN
      'p_object pg_catalog.uuid, p_subject_type pg_catalog.text, '
      'p_subject_id pg_catalog.uuid, '
      'p_subject_relation pg_catalog.text DEFAULT '''', '
      'p_any_subject pg_catalog.bool DEFAULT false, '
      'p_context pg_catalog.jsonb DEFAULT ''{}'', '
      'p_contextual_tuples pg_catalog.jsonb DEFAULT ''[]'''
  END;
$$;

CREATE OR REPLACE FUNCTION fga._compiled_arg_types(kind text)
RETURNS text
LANGUAGE sql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT CASE kind
    WHEN 'objects' THEN
      'pg_catalog.text, pg_catalog.uuid, pg_catalog.text, '
      'pg_catalog.bool, pg_catalog.jsonb, pg_catalog.jsonb'
    WHEN 'subjects' THEN
      'pg_catalog.uuid, pg_catalog.text, pg_catalog.text, '
      'pg_catalog.jsonb, pg_catalog.jsonb'
    WHEN 'check' THEN
      'pg_catalog.uuid, pg_catalog.text, pg_catalog.uuid, '
      'pg_catalog.text, pg_catalog.bool, pg_catalog.jsonb, '
      'pg_catalog.jsonb'
  END;
$$;

-- The function's definition around a body. LANGUAGE sql, STABLE,
-- SECURITY INVOKER and no SET clause: the shape PostgreSQL inlines.
CREATE OR REPLACE FUNCTION fga._compiled_ddl(
  target text, name text, kind text, body text
)
RETURNS text
LANGUAGE sql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT format(
    'CREATE OR REPLACE FUNCTION %I.%I(%s) RETURNS %s '
    'LANGUAGE sql STABLE PARALLEL SAFE SECURITY INVOKER AS %L',
    target, name, fga._compiled_params(kind),
    CASE kind WHEN 'check' THEN 'pg_catalog.bool'
              ELSE 'SETOF pg_catalog.uuid' END,
    body);
$$;

CREATE OR REPLACE FUNCTION fga._compiled_comment(
  store_id uuid, model_id uuid, type_name text, relation_name text,
  kind text, strategy text, reason text
)
RETURNS text
LANGUAGE sql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT format(
    'Compiled relation function — type: %s; relation: %s; '
    'kind: %s; store: %s; model id: %s; strategy: %s%s. This '
    'function is generated by fga4postgres from the authorization '
    'model; do not edit: every model write replaces it.',
    type_name, relation_name, kind, store_id, model_id, strategy,
    CASE WHEN reason IS NOT NULL THEN ' (' || reason || ')'
         ELSE '' END);
$$;

-- True when a call carries no contextual tuples. Flattened bodies
-- read fga.tuple only; a call with contextual tuples takes the
-- delegated path instead, so it is answered exactly, just not fast.
CREATE OR REPLACE FUNCTION fga._compiled_no_ctuples(
  contextual_tuples jsonb
)
RETURNS boolean
LANGUAGE sql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT contextual_tuples IS NULL
      OR contextual_tuples = '[]'::jsonb;
$$;

-- Raised from a __subjects body that meets a wildcard grant whose
-- subject type has no registered source: the final list cannot be
-- written, and a partial one would be wrong. The argument is a
-- column of the grant row, so the call is evaluated only when such
-- a row exists.
CREATE OR REPLACE FUNCTION fga._compiled_no_source(
  subject_type text, grant_row text
)
RETURNS boolean
LANGUAGE plpgsql
STABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
BEGIN
  RAISE EXCEPTION 'no subject source registered for type ''%'': '
    'a wildcard grant cannot be expanded into a list of subjects',
    subject_type USING ERRCODE = 'YF100',
    DETAIL = 'grant ' || grant_row;
END;
$$;

-- An emitter returns the three bodies of one relation. Each
-- strategy has its own emitter with this interface.

-- The delegated emitter: the generic resolver behind the generated
-- signature.
CREATE OR REPLACE FUNCTION fga._compiled_emit_delegated(
  store_id uuid, model_id uuid, type_name text, relation_name text,
  OUT objects_body text, OUT subjects_body text, OUT check_body text
)
LANGUAGE sql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT
    format(
      'SELECT x FROM fga._compiled_objects(%L::pg_catalog.uuid, '
      '%L::pg_catalog.uuid, %L, %L, p_subject_type, p_subject_id, '
      'p_subject_relation, p_any_subject, p_context, '
      'p_contextual_tuples) AS x',
      store_id, model_id, type_name, relation_name),
    format(
      'SELECT x FROM fga._compiled_subjects(%L::pg_catalog.uuid, '
      '%L::pg_catalog.uuid, %L, %L, p_object, p_subject_type, '
      'p_subject_relation, p_context, p_contextual_tuples) AS x',
      store_id, model_id, type_name, relation_name),
    format(
      'SELECT fga._compiled_check(%L::pg_catalog.uuid, '
      '%L::pg_catalog.uuid, %L, %L, p_object, p_subject_type, '
      'p_subject_id, p_subject_relation, p_any_subject, p_context, '
      'p_contextual_tuples)',
      store_id, model_id, type_name, relation_name);
$$;

-- The flattened emitter: a UNION of fixed joins over fga.tuple, one
-- arm per way the relation grants — the subject itself (a userset
-- subject is its own member), each direct restriction (plain,
-- wildcard, userset), each computed relation and each linked
-- parent of a tuple-to-userset. Arms that reach another relation
-- call that relation's generated function, which PostgreSQL
-- inlines in turn; the planner flattens the whole tree into one
-- query. Only relations the plan marked flattened get here: no
-- cycle, no set operation, no condition, bounded depth — so no arm
-- can raise and the union is exactly what check computes.
--
-- Stored rows are admitted like the generic read helpers admit
-- them: by the relation's restrictions (each arm names its subject
-- type and relation) and unconditioned only. Every name in a body
-- is schema-qualified, operators included, because the body runs
-- under the caller's search_path.
CREATE OR REPLACE FUNCTION fga._compiled_emit_flattened(
  store_id uuid, model_id uuid, target text,
  type_name text, relation_name text,
  OUT objects_body text, OUT subjects_body text, OUT check_body text
)
LANGUAGE plpgsql
STABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
DECLARE
  mid constant uuid := model_id;
  eq constant text := ' OPERATOR(pg_catalog.=) ';
  ne constant text := ' OPERATOR(pg_catalog.<>) ';
  nil constant text :=
    '''00000000-0000-0000-0000-000000000000''::pg_catalog.uuid';
  uncond constant text := '(g.condition_name IS NULL OR '
    'g.condition_name OPERATOR(pg_catalog.=) '''')';
  live constant text :=
    'fga._compiled_no_ctuples(p_contextual_tuples)';
  objects_args constant text := 'p_subject_type, p_subject_id, '
    'p_subject_relation, p_any_subject, p_context, '
    'p_contextual_tuples';
  subjects_args constant text := 'p_subject_type, '
    'p_subject_relation, p_context, p_contextual_tuples';
  rows_of text;
  match text;
  gate text;
  objs text[] := '{}';
  subs text[] := '{}';
  checks text[] := '{}';
  sources jsonb;
  src text[];
  d record;
  r record;
BEGIN
  SELECT cs.subject_sources INTO sources
  FROM fga.compiled_store cs WHERE cs.store = store_id;
  d := fga._compiled_emit_delegated(
    store_id, model_id, type_name, relation_name);

  -- The subject itself: T:o#R is a member of T:o#R.
  objs := objs || format(
    'SELECT p_subject_id WHERE p_subject_type%1$s%2$L '
    'AND p_subject_relation%1$s%3$L AND NOT p_any_subject',
    eq, type_name, relation_name);
  subs := subs || format(
    'SELECT p_object WHERE p_subject_type%1$s%2$L '
    'AND p_subject_relation%1$s%3$L', eq, type_name, relation_name);
  checks := checks || format(
    '(p_subject_type%1$s%2$L AND p_subject_relation%1$s%3$L '
    'AND NOT p_any_subject AND p_subject_id%1$sp_object)',
    eq, type_name, relation_name);

  -- Direct restrictions, when the rewrite assigns directly.
  rows_of := fga._compiled_rows(store_id, type_name, relation_name);
  FOR r IN
    SELECT tr.subject_type, tr.subject_relation, tr.is_wildcard
    FROM fga.model_type_restriction tr
    WHERE tr.store = store_id AND tr.model_id = mid
      AND tr.type_name = _compiled_emit_flattened.type_name
      AND tr.relation_name = _compiled_emit_flattened.relation_name
      AND EXISTS (
        SELECT FROM fga.model_relation mr,
             fga._rewrite_nodes(mr.rewrite) AS n
        WHERE mr.store = store_id AND mr.model_id = mid
          AND mr.type_name = tr.type_name
          AND mr.relation_name = tr.relation_name AND n ? 'this')
    ORDER BY tr.ord
  LOOP
    match := format('g.subject_type%1$s%2$L AND '
      'g.subject_relation%1$s%3$L', eq, r.subject_type,
      r.subject_relation);
    IF r.is_wildcard THEN
      gate := format('p_subject_type%1$s%2$L AND '
        'p_subject_relation%1$s''''', eq, r.subject_type);
      objs := objs || format(
        'SELECT g.object_id FROM fga.tuple AS g WHERE %s AND %s '
        'AND g.subject_id%s%s AND %s AND %s',
        rows_of, match, eq, nil, uncond, gate);
      checks := checks || format(
        '(%s AND EXISTS (SELECT FROM fga.tuple AS g WHERE %s AND '
        'g.object_id%sp_object AND %s AND g.subject_id%s%s AND %s))',
        gate, rows_of, eq, match, eq, nil, uncond);
      src := fga._compiled_parse_source(
        sources ->> r.subject_type);
      IF src IS NOT NULL THEN
        subs := subs || format(
          'SELECT s.%I FROM %I.%I AS s WHERE %s AND EXISTS (SELECT '
          'FROM fga.tuple AS g WHERE %s AND g.object_id%sp_object '
          'AND %s AND g.subject_id%s%s AND %s)',
          src[3], src[1], src[2], gate, rows_of, eq, match, eq, nil,
          uncond);
      ELSE
        subs := subs || format(
          'SELECT g.subject_id FROM fga.tuple AS g WHERE %s AND '
          'g.object_id%sp_object AND %s AND g.subject_id%s%s AND %s '
          'AND %s AND fga._compiled_no_source(%L, g.ulid)',
          rows_of, eq, match, eq, nil, uncond, gate, r.subject_type);
      END IF;
    ELSIF r.subject_relation = '' THEN
      gate := format('p_subject_type%1$s%2$L AND '
        'p_subject_relation%1$s''''', eq, r.subject_type);
      objs := objs || format(
        'SELECT g.object_id FROM fga.tuple AS g WHERE %s AND %s '
        'AND g.subject_id%sp_subject_id AND %s AND %s '
        'AND NOT p_any_subject', rows_of, match, eq, uncond, gate);
      checks := checks || format(
        '(%s AND NOT p_any_subject AND EXISTS (SELECT FROM '
        'fga.tuple AS g WHERE %s AND g.object_id%sp_object AND %s '
        'AND g.subject_id%sp_subject_id AND %s))',
        gate, rows_of, eq, match, eq, uncond);
      subs := subs || format(
        'SELECT g.subject_id FROM fga.tuple AS g WHERE %s AND '
        'g.object_id%sp_object AND %s AND g.subject_id%s%s AND %s '
        'AND %s', rows_of, eq, match, ne, nil, uncond, gate);
    ELSE
      objs := objs || format(
        'SELECT g.object_id FROM fga.tuple AS g WHERE %s AND %s '
        'AND %s AND g.subject_id%sANY (SELECT x FROM %s(%s) AS x)',
        rows_of, match, uncond, eq,
        fga._compiled_ref(target, r.subject_type, r.subject_relation,
                          'objects'), objects_args);
      checks := checks || format(
        'EXISTS (SELECT FROM fga.tuple AS g WHERE %s AND '
        'g.object_id%sp_object AND %s AND %s AND %s(g.subject_id, '
        '%s))', rows_of, eq, match, uncond,
        fga._compiled_ref(target, r.subject_type, r.subject_relation,
                          'check'), objects_args);
      subs := subs || format(
        'SELECT x FROM fga.tuple AS g CROSS JOIN LATERAL '
        '%s(g.subject_id, %s) AS x WHERE %s AND g.object_id%sp_object '
        'AND %s AND %s',
        fga._compiled_ref(target, r.subject_type, r.subject_relation,
                          'subjects'), subjects_args,
        rows_of, eq, match, uncond);
    END IF;
  END LOOP;

  -- Computed usersets: the same object, another relation.
  FOR r IN
    SELECT DISTINCT n -> 'computed_userset' ->> 'relation' AS rel
    FROM fga.model_relation mr, fga._rewrite_nodes(mr.rewrite) AS n
    WHERE mr.store = store_id AND mr.model_id = mid
      AND mr.type_name = _compiled_emit_flattened.type_name
      AND mr.relation_name = _compiled_emit_flattened.relation_name
      AND n ? 'computed_userset'
    ORDER BY 1
  LOOP
    objs := objs || format('SELECT x FROM %s(%s) AS x',
      fga._compiled_ref(target, type_name, r.rel, 'objects'),
      objects_args);
    checks := checks || format('%s(p_object, %s)',
      fga._compiled_ref(target, type_name, r.rel, 'check'),
      objects_args);
    subs := subs || format('SELECT x FROM %s(p_object, %s) AS x',
      fga._compiled_ref(target, type_name, r.rel, 'subjects'),
      subjects_args);
  END LOOP;

  -- Tuple-to-userset: every parent type the tupleset admits that
  -- defines the computed relation (a parent type without it adds
  -- nothing, as in check).
  FOR r IN
    SELECT DISTINCT
      n -> 'tuple_to_userset' -> 'tupleset' ->> 'relation' AS ts,
      n -> 'tuple_to_userset' -> 'computed_userset' ->> 'relation'
        AS rel,
      tr.subject_type AS parent
    FROM fga.model_relation mr, fga._rewrite_nodes(mr.rewrite) AS n
    JOIN fga.model_type_restriction tr
      ON tr.store = store_id AND tr.model_id = mid
     AND tr.type_name = _compiled_emit_flattened.type_name
     AND tr.relation_name
           = n -> 'tuple_to_userset' -> 'tupleset' ->> 'relation'
    WHERE mr.store = store_id AND mr.model_id = mid
      AND mr.type_name = _compiled_emit_flattened.type_name
      AND mr.relation_name = _compiled_emit_flattened.relation_name
      AND n ? 'tuple_to_userset'
      AND tr.subject_relation = '' AND NOT tr.is_wildcard
      AND EXISTS (
        SELECT FROM fga.model_relation p
        WHERE p.store = store_id AND p.model_id = mid
          AND p.type_name = tr.subject_type
          AND p.relation_name = n -> 'tuple_to_userset'
                -> 'computed_userset' ->> 'relation')
    ORDER BY 1, 2, 3
  LOOP
    rows_of := fga._compiled_rows(store_id, type_name, r.ts);
    match := format('g.subject_type%1$s%2$L AND '
      'g.subject_relation%1$s'''' AND g.subject_id%3$s%4$s',
      eq, r.parent, ne, nil);
    objs := objs || format(
      'SELECT g.object_id FROM fga.tuple AS g WHERE %s AND %s AND %s '
      'AND g.subject_id%sANY (SELECT x FROM %s(%s) AS x)',
      rows_of, match, uncond, eq,
      fga._compiled_ref(target, r.parent, r.rel, 'objects'),
      objects_args);
    checks := checks || format(
      'EXISTS (SELECT FROM fga.tuple AS g WHERE %s AND '
      'g.object_id%sp_object AND %s AND %s AND %s(g.subject_id, %s))',
      rows_of, eq, match, uncond,
      fga._compiled_ref(target, r.parent, r.rel, 'check'),
      objects_args);
    subs := subs || format(
      'SELECT x FROM fga.tuple AS g CROSS JOIN LATERAL '
      '%s(g.subject_id, %s) AS x WHERE %s AND g.object_id%sp_object '
      'AND %s AND %s',
      fga._compiled_ref(target, r.parent, r.rel, 'subjects'),
      subjects_args, rows_of, eq, match, uncond);
  END LOOP;

  -- Validation first (it raises, never filters), then the delegated
  -- path for contextual tuples, then the arms.
  objects_body := format(
    'SELECT NULL::pg_catalog.uuid WHERE fga._compiled_sid('
    'p_subject_id, p_any_subject, p_subject_relation) IS NULL'
    || E'\nUNION\n%s WHERE NOT %s', d.objects_body, live)
    || (SELECT string_agg(format(
         E'\nUNION\nSELECT a.x FROM (%s) AS a(x) WHERE %s', a, live),
         '' ORDER BY i)
        FROM unnest(objs) WITH ORDINALITY AS u(a, i));
  subjects_body := format(
    'SELECT NULL::pg_catalog.uuid WHERE '
    'fga._compiled_oid(p_object) IS NULL'
    || E'\nUNION\n%s WHERE NOT %s', d.subjects_body, live)
    || (SELECT string_agg(format(
         E'\nUNION\nSELECT a.x FROM (%s) AS a(x) WHERE %s', a, live),
         '' ORDER BY i)
        FROM unnest(subs) WITH ORDINALITY AS u(a, i));
  check_body := format(
    'SELECT fga._compiled_sid(p_subject_id, p_any_subject, '
    'p_subject_relation) IS NOT NULL AND fga._compiled_oid(p_object) '
    'IS NOT NULL AND CASE WHEN %s THEN (%s) ELSE (%s) END',
    live, array_to_string(checks, E'\n  OR '),
    substr(d.check_body, length('SELECT ') + 1));
END;
$$;

-- The recursive emitter: a walk over the relation's reach in the
-- tuple graph, for relations on a cycle of the relation graph (same-
-- type parent chains, nested groups, a#m -> b#m -> a#m), relations
-- reaching one, and chains deep enough to meet check's depth limit.
-- One WITH RECURSIVE body per kind covers the whole sub-graph the
-- relation reaches; its edges are VALUES lists read from the model,
-- so the body calls no other generated function. That is on
-- purpose: __check must count every dispatch from its own root, and
-- a callee's __check would start counting again at zero.
--
-- The walk's nodes are (type, object, relation); UNION deduplicates
-- them, so cyclic data ends the walk.
--   __objects walks down from the subject, like list_objects, and
--        charges no depth.
--   __check walks up from the object, recording each node's dispatch
--        count d (computed usersets cost nothing). A grant at d <= 25
--        is check's true: the shortest path to it is simple, and
--        check's search follows every simple path of up to 25
--        dispatches. Otherwise check answers false or raises YF102,
--        and it raises only from a simple path of 25 dispatches whose
--        last node has a row to dispatch, which needs both a walk row
--        at d = 26 and 26 distinct nodes (the root and 25 distinct
--        dispatch targets). Without both, false is exact; with both,
--        the generic resolver decides, so the error is check's own.
--   __subjects walks up like __check. list_users refuses as soon as
--        it enters a node 25 dispatches away, whatever it found
--        elsewhere: a walk row at d = 25 and 26 distinct nodes hand
--        the call to the generic path, anything less is exact here.
CREATE OR REPLACE FUNCTION fga._compiled_emit_recursive(
  store_id uuid, model_id uuid, target text,
  type_name text, relation_name text,
  OUT objects_body text, OUT subjects_body text, OUT check_body text
)
LANGUAGE plpgsql
STABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
DECLARE
  mid constant uuid := model_id;
  root_type constant text := type_name;
  root_rel constant text := relation_name;
  eq constant text := ' OPERATOR(pg_catalog.=) ';
  ne constant text := ' OPERATOR(pg_catalog.<>) ';
  store_lit constant text := format('%L::pg_catalog.uuid', store_id);
  nil constant text :=
    '''00000000-0000-0000-0000-000000000000''::pg_catalog.uuid';
  uncond constant text := '(g.condition_name IS NULL OR '
    'g.condition_name OPERATOR(pg_catalog.=) '''')';
  live constant text :=
    'fga._compiled_no_ctuples(p_contextual_tuples)';
  sub text[];
  direct_v text;
  userset_v text;
  computed_v text;
  ttu_v text;
  down text[] := '{}';
  seeds text[] := '{}';
  grant_at text;
  walk_check text;
  walk_subjects text;
  risky text;
  subs text[] := '{}';
  sources jsonb;
  src text[];
  d record;
  r record;
BEGIN
  SELECT cs.subject_sources INTO sources
  FROM fga.compiled_store cs WHERE cs.store = store_id;
  d := fga._compiled_emit_delegated(
    store_id, model_id, root_type, root_rel);

  -- The sub-graph: every relation the root reaches, and itself.
  WITH RECURSIVE e AS MATERIALIZED (
    SELECT * FROM fga._compiled_edges(store_id, mid)
  ), s(t, r) AS (
    SELECT root_type, root_rel
    UNION
    SELECT e.to_type, e.to_relation
    FROM s JOIN e ON e.type_name = s.t AND e.relation_name = s.r
  )
  SELECT array_agg(s.t || '#' || s.r) INTO sub FROM s;

  -- Grants that end a path: direct restrictions without a relation.
  SELECT string_agg(format('(%L::pg_catalog.text, %L::pg_catalog.text, '
      '%L::pg_catalog.text, %L::pg_catalog.bool)',
      x.t, x.r, x.st, x.wild), ', ' ORDER BY x.t, x.r, x.st, x.wild)
  INTO direct_v
  FROM (
    SELECT DISTINCT tr.type_name AS t, tr.relation_name AS r,
           tr.subject_type AS st, tr.is_wildcard AS wild
    FROM fga.model_type_restriction tr
    WHERE tr.store = store_id AND tr.model_id = mid
      AND tr.type_name || '#' || tr.relation_name = ANY (sub)
      AND tr.subject_relation = ''
      AND EXISTS (
        SELECT FROM fga.model_relation mr,
             fga._rewrite_nodes(mr.rewrite) AS n
        WHERE mr.store = store_id AND mr.model_id = mid
          AND mr.type_name = tr.type_name
          AND mr.relation_name = tr.relation_name AND n ? 'this')
  ) AS x;

  -- Userset restrictions: a dispatch to the subject's relation.
  SELECT string_agg(format('(%L::pg_catalog.text, %L::pg_catalog.text, '
      '%L::pg_catalog.text, %L::pg_catalog.text)',
      x.t, x.r, x.st, x.sr), ', ' ORDER BY x.t, x.r, x.st, x.sr)
  INTO userset_v
  FROM (
    SELECT DISTINCT tr.type_name AS t, tr.relation_name AS r,
           tr.subject_type AS st, tr.subject_relation AS sr
    FROM fga.model_type_restriction tr
    WHERE tr.store = store_id AND tr.model_id = mid
      AND tr.type_name || '#' || tr.relation_name = ANY (sub)
      AND tr.subject_relation <> ''
      AND EXISTS (
        SELECT FROM fga.model_relation mr,
             fga._rewrite_nodes(mr.rewrite) AS n
        WHERE mr.store = store_id AND mr.model_id = mid
          AND mr.type_name = tr.type_name
          AND mr.relation_name = tr.relation_name AND n ? 'this')
  ) AS x;

  -- Computed usersets: the same object, another relation.
  SELECT string_agg(format('(%L::pg_catalog.text, %L::pg_catalog.text, '
      '%L::pg_catalog.text)', x.t, x.r, x.r2), ', '
      ORDER BY x.t, x.r, x.r2)
  INTO computed_v
  FROM (
    SELECT DISTINCT mr.type_name AS t, mr.relation_name AS r,
           n -> 'computed_userset' ->> 'relation' AS r2
    FROM fga.model_relation mr, fga._rewrite_nodes(mr.rewrite) AS n
    WHERE mr.store = store_id AND mr.model_id = mid
      AND mr.type_name || '#' || mr.relation_name = ANY (sub)
      AND n ? 'computed_userset'
  ) AS x;

  -- Tuple-to-userset: each parent type the tupleset admits that
  -- defines the computed relation (a parent type without it adds
  -- nothing, as in check).
  SELECT string_agg(format('(%L::pg_catalog.text, %L::pg_catalog.text, '
      '%L::pg_catalog.text, %L::pg_catalog.text, %L::pg_catalog.text)',
      x.t, x.r, x.ts, x.pt, x.cr), ', '
      ORDER BY x.t, x.r, x.ts, x.pt, x.cr)
  INTO ttu_v
  FROM (
    SELECT DISTINCT mr.type_name AS t, mr.relation_name AS r,
      n -> 'tuple_to_userset' -> 'tupleset' ->> 'relation' AS ts,
      tr.subject_type AS pt,
      n -> 'tuple_to_userset' -> 'computed_userset' ->> 'relation'
        AS cr
    FROM fga.model_relation mr
    CROSS JOIN LATERAL fga._rewrite_nodes(mr.rewrite) AS n
    JOIN fga.model_type_restriction tr
      ON tr.store = store_id AND tr.model_id = mid
     AND tr.type_name = mr.type_name
     AND tr.relation_name
           = n -> 'tuple_to_userset' -> 'tupleset' ->> 'relation'
    WHERE mr.store = store_id AND mr.model_id = mid
      AND mr.type_name || '#' || mr.relation_name = ANY (sub)
      AND n ? 'tuple_to_userset'
      AND tr.subject_relation = '' AND NOT tr.is_wildcard
      AND EXISTS (
        SELECT FROM fga.model_relation p
        WHERE p.store = store_id AND p.model_id = mid
          AND p.type_name = tr.subject_type
          AND p.relation_name = n -> 'tuple_to_userset'
                -> 'computed_userset' ->> 'relation')
  ) AS x;

  -- __objects: down from the subject. Seeds are the rows granting
  -- it directly (a wildcard row grants every subject of its type)
  -- and, for a userset subject, the subject itself.
  IF direct_v IS NOT NULL THEN
    seeds := seeds || format(
      'SELECT a.t, g.object_id, a.r FROM (VALUES %2$s) AS a(t, r, st, '
      'wild) JOIN fga.tuple AS g ON g.store%1$s%3$s AND '
      'g.subject_type%1$sa.st AND g.subject_id%1$sCASE WHEN a.wild '
      'THEN %4$s ELSE p_subject_id END AND g.subject_relation%1$s'''' '
      'AND g.relation%1$sa.r AND g.object_type%1$sa.t '
      'WHERE a.st%1$sp_subject_type AND p_subject_relation%1$s'''' '
      'AND (a.wild OR NOT p_any_subject) AND %5$s',
      eq, direct_v, store_lit, nil, uncond);
  END IF;
  seeds := seeds || format(
    'SELECT p_subject_type, p_subject_id, p_subject_relation '
    'WHERE p_subject_relation%s'''' AND NOT p_any_subject', ne);
  IF computed_v IS NOT NULL THEN
    down := down || format(
      'SELECT c.t, w.o, c.r FROM (VALUES %2$s) AS c(t, r, r2) '
      'WHERE c.t%1$sw.t AND c.r2%1$sw.r', eq, computed_v);
  END IF;
  IF userset_v IS NOT NULL THEN
    down := down || format(
      'SELECT u.t, g.object_id, u.r FROM (VALUES %2$s) AS u(t, r, st, '
      'sr) JOIN fga.tuple AS g ON g.store%1$s%3$s AND '
      'g.subject_type%1$sw.t AND g.subject_id%1$sw.o AND '
      'g.subject_relation%1$sw.r AND g.relation%1$su.r AND '
      'g.object_type%1$su.t WHERE u.st%1$sw.t AND u.sr%1$sw.r AND %4$s',
      eq, userset_v, store_lit, uncond);
  END IF;
  IF ttu_v IS NOT NULL THEN
    down := down || format(
      'SELECT p.t, g.object_id, p.r FROM (VALUES %2$s) AS p(t, r, ts, '
      'pt, cr) JOIN fga.tuple AS g ON g.store%1$s%3$s AND '
      'g.subject_type%1$sw.t AND g.subject_id%1$sw.o AND '
      'g.subject_relation%1$s'''' AND g.relation%1$sp.ts AND '
      'g.object_type%1$sp.t WHERE p.pt%1$sw.t AND p.cr%1$sw.r AND %4$s',
      eq, ttu_v, store_lit, uncond);
  END IF;
  objects_body := format(
    E'WITH RECURSIVE w(t, o, r) AS (\n%s\nUNION\n'
    || 'SELECT n.t, n.o, n.r FROM w CROSS JOIN LATERAL (%s) AS n(t, o, r)'
    || E'\n)\nSELECT NULL::pg_catalog.uuid WHERE fga._compiled_sid('
    || 'p_subject_id, p_any_subject, p_subject_relation) IS NULL'
    || E'\nUNION\n%s WHERE NOT %s'
    || E'\nUNION\nSELECT w.o FROM w WHERE %s AND w.t%s%L AND w.r%s%L',
    array_to_string(seeds, E'\nUNION\n'),
    array_to_string(down, ' UNION ALL '),
    d.objects_body, live, live, eq, root_type, eq, root_rel);

  -- __check and __subjects: up from the object, counting dispatches
  -- up to a limit one past the counterpart's boundary.
  walk_check := fga._compiled_walk_up(store_id, root_type, root_rel,
    computed_v, userset_v, ttu_v, 26);
  walk_subjects := fga._compiled_walk_up(store_id, root_type,
    root_rel, computed_v, userset_v, ttu_v, 25);

  -- A grant at node w: w is the subject itself, or a row of w names
  -- the subject (a wildcard row any subject of its type).
  grant_at := format('(w.t%1$sp_subject_type AND w.o%1$sp_subject_id '
    'AND w.r%1$sp_subject_relation AND NOT p_any_subject)', eq);
  IF direct_v IS NOT NULL THEN
    grant_at := grant_at || format(
      ' OR EXISTS (SELECT FROM (VALUES %2$s) AS a(t, r, st, wild) '
      'JOIN fga.tuple AS g ON g.store%1$s%3$s AND g.object_type%1$sw.t '
      'AND g.object_id%1$sw.o AND g.relation%1$sw.r AND '
      'g.subject_type%1$sa.st AND g.subject_id%1$sCASE WHEN a.wild '
      'THEN %4$s ELSE p_subject_id END AND g.subject_relation%1$s'''' '
      'WHERE a.t%1$sw.t AND a.r%1$sw.r AND a.st%1$sp_subject_type AND '
      'p_subject_relation%1$s'''' AND (a.wild OR NOT p_any_subject) '
      'AND %5$s)', eq, direct_v, store_lit, nil, uncond);
  END IF;
  IF userset_v IS NOT NULL THEN
    grant_at := grant_at || format(
      ' OR EXISTS (SELECT FROM (VALUES %2$s) AS u(t, r, st, sr) '
      'JOIN fga.tuple AS g ON g.store%1$s%3$s AND g.object_type%1$sw.t '
      'AND g.object_id%1$sw.o AND g.relation%1$sw.r AND '
      'g.subject_type%1$su.st AND g.subject_id%1$sp_subject_id AND '
      'g.subject_relation%1$su.sr WHERE u.t%1$sw.t AND u.r%1$sw.r AND '
      'u.st%1$sp_subject_type AND u.sr%1$sp_subject_relation AND NOT '
      'p_any_subject AND %4$s)', eq, userset_v, store_lit, uncond);
  END IF;

  risky := '(SELECT pg_catalog.count(*) FROM (SELECT DISTINCT w.t, '
    'w.o, w.r FROM w) AS n) OPERATOR(pg_catalog.>=) 26';
  check_body := format(
    E'%s\nSELECT fga._compiled_sid(p_subject_id, p_any_subject, '
    || 'p_subject_relation) IS NOT NULL AND fga._compiled_oid(p_object) '
    'IS NOT NULL AND CASE WHEN NOT %s THEN (%s) '
    'WHEN EXISTS (SELECT FROM w WHERE w.d OPERATOR(pg_catalog.<=) 25 '
    'AND (%s)) THEN true '
    'WHEN EXISTS (SELECT FROM w WHERE w.d OPERATOR(pg_catalog.>=) 26) '
    'AND %s THEN (%s) ELSE false END',
    walk_check, live, substr(d.check_body, length('SELECT ') + 1),
    grant_at, risky, substr(d.check_body, length('SELECT ') + 1));

  -- __subjects: the nodes of the asked userset type themselves,
  -- plain rows of the asked type, and wildcard rows expanded over
  -- the registered subject source.
  subs := subs || format('SELECT w.o FROM w WHERE w.t%1$sp_subject_type '
    'AND w.r%1$sp_subject_relation', eq);
  IF direct_v IS NOT NULL THEN
    subs := subs || format(
      'SELECT g.subject_id FROM w JOIN (VALUES %2$s) AS a(t, r, st, '
      'wild) ON a.t%1$sw.t AND a.r%1$sw.r JOIN fga.tuple AS g ON '
      'g.store%1$s%3$s AND g.object_type%1$sw.t AND g.object_id%1$sw.o '
      'AND g.relation%1$sw.r AND g.subject_type%1$sa.st AND '
      'g.subject_relation%1$s'''' WHERE NOT a.wild AND '
      'a.st%1$sp_subject_type AND p_subject_relation%1$s'''' AND '
      'g.subject_id%4$s%5$s AND %6$s',
      eq, direct_v, store_lit, ne, nil, uncond);
  END IF;
  FOR r IN
    SELECT DISTINCT tr.subject_type AS st
    FROM fga.model_type_restriction tr
    WHERE tr.store = store_id AND tr.model_id = mid
      AND tr.type_name || '#' || tr.relation_name = ANY (sub)
      AND tr.is_wildcard
    ORDER BY 1
  LOOP
    src := fga._compiled_parse_source(sources ->> r.st);
    IF src IS NOT NULL THEN
      subs := subs || format(
        'SELECT s.%2$I FROM %3$I.%4$I AS s WHERE '
        'p_subject_type%1$s%5$L AND p_subject_relation%1$s'''' AND '
        'EXISTS (SELECT FROM w JOIN (VALUES %6$s) AS a(t, r, st, wild) '
        'ON a.t%1$sw.t AND a.r%1$sw.r JOIN fga.tuple AS g ON '
        'g.store%1$s%7$s AND g.object_type%1$sw.t AND '
        'g.object_id%1$sw.o AND g.relation%1$sw.r AND '
        'g.subject_type%1$sa.st AND g.subject_id%1$s%8$s AND '
        'g.subject_relation%1$s'''' WHERE a.wild AND a.st%1$s%5$L AND '
        '%9$s)', eq, src[3], src[1], src[2], r.st, direct_v,
        store_lit, nil, uncond);
    ELSE
      subs := subs || format(
        'SELECT g.subject_id FROM w JOIN (VALUES %2$s) AS a(t, r, st, '
        'wild) ON a.t%1$sw.t AND a.r%1$sw.r JOIN fga.tuple AS g ON '
        'g.store%1$s%3$s AND g.object_type%1$sw.t AND '
        'g.object_id%1$sw.o AND g.relation%1$sw.r AND '
        'g.subject_type%1$sa.st AND g.subject_id%1$s%4$s AND '
        'g.subject_relation%1$s'''' WHERE a.wild AND a.st%1$s%5$L AND '
        'p_subject_type%1$s%5$L AND p_subject_relation%1$s'''' AND %6$s '
        'AND fga._compiled_no_source(%5$L, g.ulid)',
        eq, direct_v, store_lit, nil, r.st, uncond);
    END IF;
  END LOOP;

  risky := format('(EXISTS (SELECT FROM w WHERE w.d '
    'OPERATOR(pg_catalog.>=) 25) AND %s)', risky);
  subjects_body := format(
    E'%s\nSELECT NULL::pg_catalog.uuid WHERE '
    || 'fga._compiled_oid(p_object) IS NULL'
    || E'\nUNION\n%s WHERE NOT %s OR %s', walk_subjects,
    d.subjects_body, live, risky)
    || (SELECT string_agg(format(
         E'\nUNION\nSELECT a.x FROM (%s) AS a(x) WHERE %s AND NOT %s',
         a, live, risky), '' ORDER BY i)
        FROM unnest(subs) WITH ORDINALITY AS u(a, i));
END;
$$;

-- The upward walk shared by __check and __subjects: a WITH RECURSIVE
-- named w(t, o, r, d) from the generated function's p_object, where
-- d counts dispatches; a node at the limit dispatches no further,
-- which ends the walk on cyclic data too.
CREATE OR REPLACE FUNCTION fga._compiled_walk_up(
  store_id uuid, root_type text, root_rel text,
  computed_v text, userset_v text, ttu_v text, depth_limit integer
)
RETURNS text
LANGUAGE plpgsql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
DECLARE
  eq constant text := ' OPERATOR(pg_catalog.=) ';
  store_lit constant text := format('%L::pg_catalog.uuid', store_id);
  next_d constant text := 'w.d OPERATOR(pg_catalog.+) 1';
  below constant text := format('w.d OPERATOR(pg_catalog.<) %s',
    depth_limit);
  uncond constant text := '(g.condition_name IS NULL OR '
    'g.condition_name OPERATOR(pg_catalog.=) '''')';
  up text[] := '{}';
BEGIN
  IF computed_v IS NOT NULL THEN
    up := up || format(
      'SELECT w.t, w.o, c.r2, w.d FROM (VALUES %2$s) AS c(t, r, r2) '
      'WHERE c.t%1$sw.t AND c.r%1$sw.r', eq, computed_v);
  END IF;
  IF userset_v IS NOT NULL THEN
    up := up || format(
      'SELECT g.subject_type, g.subject_id, g.subject_relation, %5$s '
      'FROM (VALUES %2$s) AS u(t, r, st, sr) JOIN fga.tuple AS g ON '
      'g.store%1$s%3$s AND g.object_type%1$sw.t AND g.object_id%1$sw.o '
      'AND g.relation%1$sw.r AND g.subject_type%1$su.st AND '
      'g.subject_relation%1$su.sr WHERE u.t%1$sw.t AND u.r%1$sw.r AND '
      '%6$s AND %4$s', eq, userset_v, store_lit, uncond, next_d, below);
  END IF;
  IF ttu_v IS NOT NULL THEN
    up := up || format(
      'SELECT p.pt, g.subject_id, p.cr, %5$s FROM (VALUES %2$s) AS '
      'p(t, r, ts, pt, cr) JOIN fga.tuple AS g ON g.store%1$s%3$s AND '
      'g.object_type%1$sw.t AND g.object_id%1$sw.o AND '
      'g.relation%1$sp.ts AND g.subject_type%1$sp.pt AND '
      'g.subject_relation%1$s'''' AND g.subject_id '
      'OPERATOR(pg_catalog.<>) '
      '''00000000-0000-0000-0000-000000000000''::pg_catalog.uuid '
      'WHERE p.t%1$sw.t AND p.r%1$sw.r AND %6$s AND %4$s',
      eq, ttu_v, store_lit, uncond, next_d, below);
  END IF;
  RETURN format(
    E'WITH RECURSIVE w(t, o, r, d) AS (\nSELECT %L::pg_catalog.text, '
    || E'p_object, %L::pg_catalog.text, 0\nUNION\n'
    'SELECT n.t, n.o, n.r, n.d FROM w CROSS JOIN LATERAL (%s) '
    || E'AS n(t, o, r, d)\n)',
    root_type, root_rel, array_to_string(up, ' UNION ALL '));
END;
$$;

-- "g.store = S AND g.object_type = T AND g.relation = R" for one
-- (type, relation), qualified.
CREATE OR REPLACE FUNCTION fga._compiled_rows(
  store_id uuid, type_name text, relation_name text
)
RETURNS text
LANGUAGE sql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT format(
    'g.store%1$s%2$L::pg_catalog.uuid AND g.object_type%1$s%3$L '
    'AND g.relation%1$s%4$L',
    ' OPERATOR(pg_catalog.=) ', store_id, type_name, relation_name);
$$;

-- The qualified name of another relation's generated function.
CREATE OR REPLACE FUNCTION fga._compiled_ref(
  target text, type_name text, relation_name text, kind text
)
RETURNS text
LANGUAGE sql
IMMUTABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT format('%I.%I', target,
    fga._compiled_name(type_name, relation_name, kind));
$$;

-- The edges of a model's relation graph: a relation points at every
-- relation its rewrite can reach in one step — a computed userset
-- (same object, hop 0), a userset restriction or a tuple-to-userset
-- parent that defines the computed relation (another object, hop 1:
-- a dispatch, the only step that spends check's depth budget).
CREATE OR REPLACE FUNCTION fga._compiled_edges(
  store_id uuid, model_id uuid
)
RETURNS TABLE (type_name text, relation_name text, to_type text,
               to_relation text, hop integer)
LANGUAGE sql
STABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  WITH
  rel AS (
    SELECT r.type_name, r.relation_name, r.rewrite
    FROM fga.model_relation r
    WHERE r.store = store_id AND r.model_id = _compiled_edges.model_id
  ),
  node AS (
    SELECT rel.type_name, rel.relation_name, n
    FROM rel, fga._rewrite_nodes(rel.rewrite) AS n
  ),
  restriction AS (
    SELECT tr.* FROM fga.model_type_restriction tr
    WHERE tr.store = store_id
      AND tr.model_id = _compiled_edges.model_id
  )
  SELECT nd.type_name, nd.relation_name, nd.type_name AS to_type,
         nd.n -> 'computed_userset' ->> 'relation' AS to_relation,
         0 AS hop
  FROM node nd WHERE nd.n ? 'computed_userset'
  UNION ALL
  SELECT nd.type_name, nd.relation_name, tr.subject_type,
         nd.n -> 'tuple_to_userset' -> 'computed_userset'
           ->> 'relation', 1
  FROM node nd
  JOIN restriction tr
    ON tr.type_name = nd.type_name
   AND tr.relation_name
         = nd.n -> 'tuple_to_userset' -> 'tupleset' ->> 'relation'
  JOIN rel p
    ON p.type_name = tr.subject_type
   AND p.relation_name = nd.n -> 'tuple_to_userset'
         -> 'computed_userset' ->> 'relation'
  WHERE nd.n ? 'tuple_to_userset'
    AND tr.subject_relation = '' AND NOT tr.is_wildcard
  UNION ALL
  SELECT nd.type_name, nd.relation_name, tr.subject_type,
         tr.subject_relation, 1
  FROM node nd
  JOIN restriction tr
    ON tr.type_name = nd.type_name
   AND tr.relation_name = nd.relation_name
  WHERE nd.n ? 'this' AND tr.subject_relation <> '';
$$;

-- The strategy of every relation of a model, the reason a
-- relation is delegated, and the order to create functions in
-- (callees before callers).
--
-- A relation flattens when its rewrite is only unions of direct
-- grants, computed usersets and tuple-to-usersets, it grants
-- through no condition, and every relation it reaches flattens
-- too. A relation on a cycle of the relation graph — or reaching
-- one — or whose dispatch chain may reach the resolution limit
-- compiles to the recursive strategy instead, when nothing it
-- reaches needs delegation for another reason.
CREATE OR REPLACE FUNCTION fga._compiled_plan(
  store_id uuid, model_id uuid
)
RETURNS TABLE (type_name text, relation_name text, strategy text,
               reason text, ord integer)
LANGUAGE sql
STABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  WITH RECURSIVE
  rel AS (
    SELECT r.type_name, r.relation_name, r.rewrite, r.needs_check
    FROM fga.model_relation r
    WHERE r.store = store_id AND r.model_id = _compiled_plan.model_id
  ),
  node AS (
    SELECT rel.type_name, rel.relation_name, n
    FROM rel, fga._rewrite_nodes(rel.rewrite) AS n
  ),
  restriction AS (
    SELECT tr.* FROM fga.model_type_restriction tr
    WHERE tr.store = store_id AND tr.model_id = _compiled_plan.model_id
  ),
  edge AS (
    SELECT * FROM fga._compiled_edges(store_id, _compiled_plan.model_id)
  ),
  own AS (
    SELECT rel.type_name, rel.relation_name, CASE
      WHEN rel.needs_check THEN 'intersection or exclusion'
      WHEN EXISTS (
        SELECT FROM node nd JOIN restriction tr
          ON tr.type_name = nd.type_name
         AND tr.relation_name = nd.relation_name
        WHERE nd.type_name = rel.type_name
          AND nd.relation_name = rel.relation_name
          AND nd.n ? 'this' AND tr.condition_name <> ''
      ) THEN 'conditioned grant'
      WHEN EXISTS (
        SELECT FROM node nd JOIN restriction tr
          ON tr.type_name = nd.type_name
         AND tr.relation_name
               = nd.n -> 'tuple_to_userset' -> 'tupleset' ->> 'relation'
        WHERE nd.type_name = rel.type_name
          AND nd.relation_name = rel.relation_name
          AND (tr.condition_name <> '' OR tr.is_wildcard
               OR tr.subject_relation <> '')
      ) THEN 'conditioned or indirect tupleset'
      WHEN EXISTS (
        SELECT FROM node nd
        WHERE nd.type_name = rel.type_name
          AND nd.relation_name = rel.relation_name
          AND NOT (nd.n ?| ARRAY['this', 'union', 'computed_userset',
                                 'tuple_to_userset'])
      ) THEN 'unsupported rewrite'
    END AS reason
    FROM rel
  ),
  reach AS (
    SELECT e.type_name, e.relation_name, e.to_type, e.to_relation
    FROM edge e
    UNION
    SELECT x.type_name, x.relation_name, e.to_type, e.to_relation
    FROM reach x
    JOIN edge e
      ON e.type_name = x.to_type AND e.relation_name = x.to_relation
  ),
  bad AS (
    SELECT o.type_name, o.relation_name, coalesce(o.reason, CASE
      WHEN EXISTS (
        SELECT FROM reach x
        WHERE x.type_name = o.type_name
          AND x.relation_name = o.relation_name
          AND x.to_type = o.type_name
          AND x.to_relation = o.relation_name)
      THEN 'recursive: on a cycle of the relation graph'
    END) AS reason
    FROM own o
  ),
  verdict AS (
    SELECT b.type_name, b.relation_name, coalesce(b.reason, (
      SELECT 'reaches ' || x.to_type || '#' || x.to_relation
             || ' (' || bb.reason || ')'
      FROM reach x
      JOIN bad bb
        ON bb.type_name = x.to_type
       AND bb.relation_name = x.to_relation
      WHERE x.type_name = b.type_name
        AND x.relation_name = b.relation_name
        AND bb.reason IS NOT NULL
      ORDER BY 1 LIMIT 1)) AS reason
    FROM bad b
  ),
  -- Paths from every compilable relation; they reach no cycle, so
  -- the walk ends. hops is the dispatch depth, len the call depth.
  walk AS (
    SELECT v.type_name AS root_type, v.relation_name AS root_relation,
           v.type_name, v.relation_name, 0 AS hops, 0 AS len
    FROM verdict v WHERE v.reason IS NULL
    UNION
    SELECT w.root_type, w.root_relation, e.to_type, e.to_relation,
           w.hops + e.hop, w.len + 1
    FROM walk w
    JOIN edge e
      ON e.type_name = w.type_name
     AND e.relation_name = w.relation_name
    WHERE w.hops < 25
  ),
  depth AS (
    SELECT w.root_type, w.root_relation,
           max(w.hops) AS hops, max(w.len) AS len
    FROM walk w GROUP BY 1, 2
  )
  SELECT v.type_name, v.relation_name, k.strategy,
    CASE WHEN k.strategy = 'delegated' THEN b.reason END,
    CASE WHEN k.strategy = 'flattened' THEN 1 + d.len ELSE 0 END
  FROM verdict v
  LEFT JOIN depth d
    ON d.root_type = v.type_name AND d.root_relation = v.relation_name
  -- What only the generic resolver answers, in the relation or in
  -- anything it reaches. A cycle or a deep chain is not on this
  -- list: the recursive strategy takes those.
  CROSS JOIN LATERAL (SELECT coalesce((
      SELECT o.reason FROM own o
      WHERE o.type_name = v.type_name
        AND o.relation_name = v.relation_name), (
      SELECT 'reaches ' || x.to_type || '#' || x.to_relation
             || ' (' || o.reason || ')'
      FROM reach x
      JOIN own o
        ON o.type_name = x.to_type AND o.relation_name = x.to_relation
      WHERE x.type_name = v.type_name
        AND x.relation_name = v.relation_name
        AND o.reason IS NOT NULL
      ORDER BY 1 LIMIT 1)) AS reason) AS b
  CROSS JOIN LATERAL (SELECT CASE
    WHEN v.reason IS NULL AND d.hops < 24 THEN 'flattened'
    WHEN b.reason IS NULL THEN 'recursive'
    ELSE 'delegated' END AS strategy) AS k;
$$;

-- The note a relation's registry reason carries when its
-- __subjects may meet a wildcard grant of a type the store has
-- registered no subject source for: such a call raises rather than
-- return a partial list, and the registry says so from the model
-- write on. NULL when every wildcard the relation can reach — on
-- itself, through computed usersets, tuple-to-usersets or userset
-- grants — has a source.
CREATE OR REPLACE FUNCTION fga._compiled_source_note(
  store_id uuid, model_id uuid, type_name text, relation_name text
)
RETURNS text
LANGUAGE sql
STABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  WITH RECURSIVE
  node AS (
    SELECT r.type_name, r.relation_name, n
    FROM fga.model_relation r, fga._rewrite_nodes(r.rewrite) AS n
    WHERE r.store = store_id
      AND r.model_id = _compiled_source_note.model_id
  ),
  restriction AS (
    SELECT tr.* FROM fga.model_type_restriction tr
    WHERE tr.store = store_id
      AND tr.model_id = _compiled_source_note.model_id
  ),
  edge AS (
    SELECT nd.type_name, nd.relation_name, nd.type_name AS to_type,
           nd.n -> 'computed_userset' ->> 'relation' AS to_relation
    FROM node nd WHERE nd.n ? 'computed_userset'
    UNION ALL
    SELECT nd.type_name, nd.relation_name, tr.subject_type,
           nd.n -> 'tuple_to_userset' -> 'computed_userset'
             ->> 'relation'
    FROM node nd
    JOIN restriction tr
      ON tr.type_name = nd.type_name
     AND tr.relation_name
           = nd.n -> 'tuple_to_userset' -> 'tupleset' ->> 'relation'
    WHERE nd.n ? 'tuple_to_userset'
      AND tr.subject_relation = '' AND NOT tr.is_wildcard
    UNION ALL
    SELECT nd.type_name, nd.relation_name, tr.subject_type,
           tr.subject_relation
    FROM node nd
    JOIN restriction tr
      ON tr.type_name = nd.type_name
     AND tr.relation_name = nd.relation_name
    WHERE nd.n ? 'this' AND tr.subject_relation <> ''
  ),
  reach AS (
    SELECT _compiled_source_note.type_name,
           _compiled_source_note.relation_name
    UNION
    SELECT e.to_type, e.to_relation
    FROM reach x
    JOIN edge e
      ON e.type_name = x.type_name
     AND e.relation_name = x.relation_name
  )
  SELECT '__subjects: no subject source registered for wildcard '
    || 'type ' || string_agg(DISTINCT tr.subject_type, ', '
                             ORDER BY tr.subject_type)
  FROM reach x
  JOIN restriction tr
    ON tr.type_name = x.type_name
   AND tr.relation_name = x.relation_name
  WHERE tr.is_wildcard
    AND EXISTS (
      SELECT FROM node nd
      WHERE nd.type_name = x.type_name
        AND nd.relation_name = x.relation_name AND nd.n ? 'this')
    AND NOT EXISTS (
      SELECT FROM fga.compiled_store cs
      WHERE cs.store = store_id
        AND cs.subject_sources ? tr.subject_type);
$$;

-- Every function of a model: names, signatures and definitions,
-- each body from its relation's strategy emitter.
CREATE OR REPLACE FUNCTION fga._compiled_functions(
  store_id uuid, model_id uuid, target text
)
RETURNS TABLE (type_name text, relation_name text, kind text,
               name text, sig text, ddl text, strategy text,
               reason text, ord integer)
LANGUAGE sql
STABLE PARALLEL SAFE
SET search_path = fga, pg_temp
AS $$
  SELECT p.type_name, p.relation_name, k.kind, n.name,
    format('%I.%I(%s)', target, n.name,
           fga._compiled_arg_types(k.kind)),
    fga._compiled_ddl(target, n.name, k.kind, CASE k.kind
      WHEN 'objects' THEN b.objects_body
      WHEN 'subjects' THEN b.subjects_body
      ELSE b.check_body END),
    p.strategy,
    nullif(concat_ws('; ', p.reason, fga._compiled_source_note(
      store_id, model_id, p.type_name, p.relation_name)), ''),
    p.ord
  FROM fga._compiled_plan(store_id, model_id) AS p
  CROSS JOIN LATERAL (
    SELECT * FROM fga._compiled_emit_flattened(store_id, model_id,
      target, p.type_name, p.relation_name)
    WHERE p.strategy = 'flattened'
    UNION ALL
    SELECT * FROM fga._compiled_emit_recursive(store_id, model_id,
      target, p.type_name, p.relation_name)
    WHERE p.strategy = 'recursive'
    UNION ALL
    SELECT * FROM fga._compiled_emit_delegated(store_id, model_id,
      p.type_name, p.relation_name)
    WHERE p.strategy = 'delegated'
  ) AS b
  CROSS JOIN (VALUES ('objects'), ('subjects'), ('check')) AS k(kind)
  CROSS JOIN LATERAL (SELECT fga._compiled_name(
    p.type_name, p.relation_name, k.kind) AS name) AS n;
$$;

-- Drops every registered function of a store and its registry
-- rows. Only registered functions: anything else in the schema
-- belongs to the application.
CREATE OR REPLACE FUNCTION fga._compiled_drop(store_id uuid)
RETURNS void
LANGUAGE plpgsql
VOLATILE
SET search_path = fga, pg_temp
AS $$
DECLARE
  fn regprocedure;
BEGIN
  FOR fn IN
    SELECT DISTINCT v.f
    FROM fga.compiled_relation r,
         LATERAL (VALUES (r.objects_fn), (r.subjects_fn),
                         (r.check_fn)) AS v(f)
    WHERE r.store = store_id
  LOOP
    EXECUTE format('DROP FUNCTION %s', fn);
  END LOOP;
  DELETE FROM fga.compiled_relation WHERE store = store_id;
END;
$$;

-- Regenerates every function of an opted-in store from its latest
-- model, in the caller's transaction. A no-op for stores that did
-- not opt in.
--
-- Functions that survive a model change are replaced in place
-- (CREATE OR REPLACE keeps their oid, so a cached plan that inlined
-- one is invalidated and re-planned rather than left pointing at a
-- dropped function); only registered functions the new model no
-- longer has are dropped. A same-signature function the engine did
-- not register belongs to the application: it refuses the model
-- write instead of being overwritten.
CREATE OR REPLACE FUNCTION fga._compiled_generate(store_id uuid)
RETURNS void
LANGUAGE plpgsql
VOLATILE
SET search_path = fga, pg_temp
AS $$
DECLARE
  target text;
  mid uuid;
  fns jsonb;
  fn record;
  clash text;
BEGIN
  SELECT cs.target_schema INTO target
  FROM fga.compiled_store cs WHERE cs.store = store_id;
  IF NOT FOUND THEN
    RETURN;
  END IF;

  SELECT m.id INTO mid FROM fga.model m
  WHERE m.store = store_id ORDER BY m.id DESC LIMIT 1;

  SELECT coalesce(jsonb_agg(to_jsonb(f) ORDER BY f.ord, f.name),
                  '[]')
  INTO fns
  FROM fga._compiled_functions(store_id, mid, target) AS f
  WHERE mid IS NOT NULL;

  SELECT f ->> 'name' INTO clash
  FROM jsonb_array_elements(fns) AS f
  GROUP BY f ->> 'name' HAVING count(*) > 1 LIMIT 1;
  IF clash IS NOT NULL THEN
    RAISE EXCEPTION 'compiled relations: two relations would share '
      'the function name %', clash USING ERRCODE = 'YF156';
  END IF;

  -- Drop what was registered and is no longer generated.
  FOR fn IN
    SELECT DISTINCT v.f
    FROM fga.compiled_relation r,
         LATERAL (VALUES (r.objects_fn), (r.subjects_fn),
                         (r.check_fn)) AS v(f)
    WHERE r.store = store_id
      AND NOT EXISTS (
        SELECT FROM jsonb_array_elements(fns) AS g
        WHERE to_regprocedure(g ->> 'sig') = v.f)
  LOOP
    EXECUTE format('DROP FUNCTION %s', fn.f);
  END LOOP;

  SELECT g ->> 'sig' INTO clash
  FROM jsonb_array_elements(fns) AS g
  WHERE to_regprocedure(g ->> 'sig') IS NOT NULL
    AND NOT EXISTS (
      SELECT FROM fga.compiled_relation r
      WHERE r.store = store_id
        AND to_regprocedure(g ->> 'sig')
              IN (r.objects_fn, r.subjects_fn, r.check_fn))
  LIMIT 1;
  IF clash IS NOT NULL THEN
    RAISE EXCEPTION 'compiled relations: function % exists and was '
      'not generated by fga4postgres', clash
      USING ERRCODE = 'YF156';
  END IF;

  DELETE FROM fga.compiled_relation WHERE store = store_id;

  FOR fn IN
    SELECT * FROM jsonb_to_recordset(fns) AS x(
      type_name text, relation_name text, kind text, name text,
      sig text, ddl text, strategy text, reason text)
  LOOP
    EXECUTE fn.ddl;
    EXECUTE format('COMMENT ON FUNCTION %s IS %L', fn.sig,
      fga._compiled_comment(store_id, mid, fn.type_name,
        fn.relation_name, fn.kind, fn.strategy, fn.reason));
  END LOOP;

  INSERT INTO fga.compiled_relation
  SELECT store_id, mid, x.type_name, x.relation_name,
    max(x.sig) FILTER (WHERE x.kind = 'objects')::regprocedure,
    max(x.sig) FILTER (WHERE x.kind = 'subjects')::regprocedure,
    max(x.sig) FILTER (WHERE x.kind = 'check')::regprocedure,
    min(x.strategy), min(x.reason)
  FROM jsonb_to_recordset(fns) AS x(
    type_name text, relation_name text, kind text, sig text,
    strategy text, reason text)
  GROUP BY x.type_name, x.relation_name;
END;
$$;

-- Opts a store in (or changes its subject sources) and generates
-- its functions for the latest model right away. The schema must
-- already exist: the application creates and owns it, so the
-- engine needs no database-level CREATE and a mistyped name is an
-- error rather than a new empty schema.
CREATE OR REPLACE FUNCTION fga.enable_compiled_relations(
  store uuid,
  target_schema text,
  subject_sources jsonb DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
VOLATILE
SET search_path = fga, pg_temp
AS $$
DECLARE
  src record;
  m text[];
BEGIN
  IF NOT EXISTS (
    SELECT FROM fga.store s
    WHERE s.id = enable_compiled_relations.store
  ) THEN
    RAISE EXCEPTION 'store % not found', enable_compiled_relations.store
      USING ERRCODE = 'YF502';
  END IF;
  IF target_schema IN ('fga', 'cel', 'information_schema')
     OR target_schema LIKE 'pg\_%' THEN
    RAISE EXCEPTION 'schema ''%'' is reserved: compiled relations '
      'need a schema of their own', target_schema
      USING ERRCODE = 'YF100';
  END IF;
  IF NOT EXISTS (
    SELECT FROM pg_namespace n WHERE n.nspname = target_schema
  ) THEN
    RAISE EXCEPTION 'schema ''%'' does not exist: create it before '
      'enabling compiled relations', target_schema
      USING ERRCODE = 'YF100';
  END IF;
  IF EXISTS (
    SELECT FROM fga.compiled_store cs
    WHERE cs.target_schema = enable_compiled_relations.target_schema
      AND cs.store <> enable_compiled_relations.store
  ) THEN
    RAISE EXCEPTION 'schema ''%'' already holds another store''s '
      'compiled relations', target_schema USING ERRCODE = 'YF100';
  END IF;

  IF subject_sources IS NOT NULL THEN
    IF jsonb_typeof(subject_sources) <> 'object' THEN
      RAISE EXCEPTION 'subject_sources must be a json object'
        USING ERRCODE = 'YF100';
    END IF;
    FOR src IN SELECT * FROM jsonb_each(subject_sources) LOOP
      m := fga._compiled_parse_source(src.value #>> '{}');
      IF jsonb_typeof(src.value) <> 'string' OR m IS NULL
         OR NOT EXISTS (
           SELECT FROM pg_attribute a
           WHERE a.attrelid = to_regclass(
                   format('%I.%I', m[1], m[2]))
             AND a.attname = m[3] AND NOT a.attisdropped
             AND a.atttypid = 'uuid'::regtype
         )
      THEN
        RAISE EXCEPTION 'subject source for type ''%'' must name '
          'an existing uuid column as schema.table(column), got %',
          src.key, src.value USING ERRCODE = 'YF100';
      END IF;
    END LOOP;
  END IF;

  -- A different schema means the old functions go first.
  IF EXISTS (
    SELECT FROM fga.compiled_store cs
    WHERE cs.store = enable_compiled_relations.store
      AND cs.target_schema <> enable_compiled_relations.target_schema
  ) THEN
    PERFORM fga._compiled_drop(enable_compiled_relations.store);
  END IF;

  INSERT INTO fga.compiled_store AS cs
  VALUES (enable_compiled_relations.store, target_schema,
          subject_sources)
  ON CONFLICT ON CONSTRAINT compiled_store_pkey DO UPDATE
  SET target_schema = excluded.target_schema,
      subject_sources = excluded.subject_sources;

  PERFORM fga._compiled_generate(enable_compiled_relations.store);
END;
$$;

-- Opts a store out: drops exactly its registered functions.
CREATE OR REPLACE FUNCTION fga.disable_compiled_relations(
  store uuid
)
RETURNS void
LANGUAGE plpgsql
VOLATILE
SET search_path = fga, pg_temp
AS $$
BEGIN
  PERFORM fga._compiled_drop(disable_compiled_relations.store);
  DELETE FROM fga.compiled_store cs
  WHERE cs.store = disable_compiled_relations.store;
END;
$$;
